name: 주현이 슈팅게임 윈도우 실행 파일 만들기

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pyinstaller

      - name: Copy Python files and Build EXE with PyInstaller
        run: |
          pyinstaller -F --onefile shooting_game.py

      - name: Upload shooting_game.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: shooting-game-assets
          path: |
            dist/shooting_game.exe
            dist/background_music.mp3
            dist/background.jpg
            dist/fighter.png
